services:
  backend:
    build: ./backend
    expose:
      - "8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080"] 
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
  
  frontend:
    image: nginx:latest
    container_name: frontendcont
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro